services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    depends_on:
      - znc
      - app
      - geoip
    ports:
      - 443:443
      - 80:80
      - 6969:6969
      - 7000:7000
    volumes:
      - /home/iq/Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/iqun.xyz/fullchain.pem:/etc/nginx/ssl/live/iqun.xyz/fullchain.pem
      - /etc/letsencrypt/live/iqun.xyz/privkey.pem:/etc/nginx/ssl/live/iqun.xyz/privkey.pem
      - /home/iq/tenzies:/etc/nginx/html/tenzies:rw
      - nginx_cache:/var/cache/nginx
    restart: always
    networks:
      - backend
      - external
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    #ports:
    #     - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  znc:
    image: znc:latest
    container_name: znc
    volumes:
      - /home/iq/.znc:/znc-data:rw
    restart: always
    networks:
      - backend
  app:
    image: iqunlim/iqun.xyz:latest
    container_name: app
    pull_policy: always
    #ports:
    #- 3000:3000
    restart: always
    env_file:
      - .env
    networks:
      - backend
  geoip:
    image: observabilitystack/geoip-api
    container_name: geoip
    pull_policy: always
    #ports:
    #  - 8080:8080
    networks:
      - backend

networks:
  backend:
    driver: bridge
  external:
    driver: bridge

volumes:
  postgres_data:
    external: true
  nginx_cache:
