services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: sitedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    # image: "iqunlim/iqun.xyz:latest"
    pull_policy: always
    container_name: site
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

    ports:
      - "3000:3000"
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
